name: ui
description: Conduit UI
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  conduit_client:
    path: '../client'
  flutter:
    sdk: flutter
  flutter_riverpod: ^0.14.0+1
  flutter_web_plugins:
    sdk: flutter
  intl: ^0.17.0
  shared_preferences: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: Titillium
      fonts:
        - asset: fonts/TitilliumWeb-Regular.ttf
        - asset: fonts/TitilliumWeb-Bold.ttf
          weight: 700
    - family: Source Sans Pro
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf
        - asset: fonts/SourceSansPro-Bold.ttf
          weight: 700