name: ui
description: Conduit UI
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.13.0-0 <3.0.0"

dependencies:
  conduit_client:
    path: '../client'
  flutter:
    sdk: flutter
  flutter_riverpod: ^0.14.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Titillium
      fonts:
        - asset: fonts/TitilliumWeb-Regular.ttf
        - asset: fonts/TitilliumWeb-Bold.ttf
          weight: 700
    - family: Source Sans Pro
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf
        - asset: fonts/SourceSansPro-Bold.ttf
          weight: 700