name: ui
description: Conduit UI
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.13.0-0 <3.0.0"

dependencies:
  conduit_client:
    path: '../client'
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true